Skip to content
￼￼
Pull requests
Issues
Marketplace
Explore
 
￼ 
Learn Git and GitHub without any code!
Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.

Read the guide
￼
saeson001
/
lede
forked from coolsnowwolf/lede
 Watch 0
￼ Star0 Fork6.4k
 Code Pull requests 0 Actions Projects 0 Wiki Security Insights Settings
lede
/
.github
/
workflows
/
￼
Cancel
￼ Edit file ￼ Preview changes
￼￼￼
1
#
2
# This is free software, lisence use MIT.
3
# 
4
# Copyright (C) 2019 P3TERX <https://p3terx.com>
5
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
6
# 
7
# <https://github.com/KFERMercer/OpenWrt-CI>
8
#
9
​
10
name: OpenWrt-CI
11
​
12
on:
13
  push:
14
    branches: 
15
      - master
16
  # schedule:
17
  #   - cron: 0 20 * * *
18
  # release:
19
  #   types: [published]
20
​
21
jobs:
22
​
23
  build:
24
​
25
    runs-on: ubuntu-latest
26
​
27
    steps:
28
​
29
      - name: Checkout
30
        uses: actions/checkout@master
Use Control + Space to trigger autocomplete in most situations.
￼ Marketplace
￼ Documentation
￼
Featured Actions
￼
￼ Cache
By actions 

Cache artifacts like dependencies and build outputs to improve workflow execution time

 769
￼
￼ Setup Node.js for use with actions
By actions 

Setup a Node.js environment and add it to the PATH, additionally providing proxy support

 314
￼
￼ Upload artifact
By actions 

Publish files as workflow artifacts

 288
￼
￼ Close Stale Issues
By actions 

Action to close stale issues

 113
￼
￼ Setup Ruby for use with actions
By actions 

Setup a Ruby environment and add it to the PATH

 74
Featured categories
￼ Code quality
￼ Continuous integration
￼ Deployment
￼ Monitoring
￼ Project management
￼ Testing
Browse all actions on the GitHub Marketplace
Start commit 
